var $jscomp={scope:{},executeAsyncGenerator:function(a){function c(b){return a.next(b)}function b(b){return a.throw(b)}return new Promise(function(h,f){function e(a){a.done?h(a.value):Promise.resolve(a.value).then(c,b).then(e,f)}e(a.next())})}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
var modalHealthInsurance=$("#modalHealthInsurance"),formHealthInsurance=$("#formHealthInsurance"),tblStudentClass=$("#tblStudentClass"),tblStatusDecision=$("#tblStatusDecision"),jTblCourseRegResult=$("#tblCourseRegResult"),jTblTuitionFeeHistory=$("#tblTuitionFeeHistory"),jTblActivities=$("#tblActivities"),jTtblQnAThread=$("#tblQnAThread"),jModalQnAContent=$("#modalQnAContent"),studentInfo,studentProfile,studentHealthInsurance,language,courseRegResults,tuitionFeesHistory,qnaHistory,activities,statusDecisions;
$(document).ready(function(){return $jscomp.executeAsyncGenerator(function(){function a(a,d){for(;;)switch(c){case 0:g=$("#idSV").val();n=$("#root_URL").val();language=$("#hid_Language").val();$("#btnBack").on("click",function(a){a.preventDefault();1<window.history.length?history.go(-1):window.location.href=n+"/he-thong-quan-ly-hoc-vu/quan-ly-sinh-vien/ho-so-sinh-vien"});if(!g){c=1;break}c=3;return{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/detail-info/"+g,"GET",null,function(b){return a(b)})}),
done:!1};case 3:if(void 0===d){c=4;break}c=-1;throw d;case 4:return studentInfo=u=a,c=5,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/detail-profile/"+g,"GET",null,function(b){return a(b)})}),done:!1};case 5:if(void 0===d){c=6;break}c=-1;throw d;case 6:return studentProfile=v=a,c=7,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/health-insurance/detail/"+g,"GET",null,function(b){return a(b)})}),done:!1};case 7:if(void 0===d){c=8;break}c=-1;throw d;case 8:return studentHealthInsurance=
w=a,c=9,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/course-register-results/by-student-code/"+studentInfo.code,"GET",null,function(b){return a(b)})}),done:!1};case 9:if(void 0===d){c=10;break}c=-1;throw d;case 10:return courseRegResults=x=a,c=11,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/tuition-fees/by-student-code/"+studentInfo.code,"GET",null,function(b){return a(b)})}),done:!1};case 11:if(void 0===d){c=12;break}c=-1;throw d;case 12:return tuitionFeesHistory=y=a,c=13,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student-helpdesk/qna-history/by-student-code/"+
studentInfo.code,"GET",null,function(b){return a(b)})}),done:!1};case 13:if(void 0===d){c=14;break}c=-1;throw d;case 14:return qnaHistory=z=a,c=15,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student-activities/social-workdays/by-student-code/"+studentInfo.code,"GET",null,function(b){return a(b)})}),done:!1};case 15:if(void 0===d){c=16;break}c=-1;throw d;case 16:return activities=A=a,c=17,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/status-decision/by-student-code/"+studentInfo.code,
"GET",null,function(b){return a(b)})}),done:!1};case 17:if(void 0===d){c=18;break}c=-1;throw d;case 18:statusDecisions=B=a;c=2;break;case 1:return c=19,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/get-student-info","GET",null,function(b){return a(b)})}),done:!1};case 19:if(void 0===d){c=20;break}c=-1;throw d;case 20:return studentInfo=C=a,c=21,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/get-student-profile","GET",null,function(b){return a(b)})}),done:!1};case 21:if(void 0===
d){c=22;break}c=-1;throw d;case 22:return studentProfile=D=a,g=studentInfo.id,c=23,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/student/health-insurance/detail/"+g,"GET",null,function(b){return a(b)})}),done:!1};case 23:if(void 0===d){c=24;break}c=-1;throw d;case 24:studentHealthInsurance=E=a;case 2:return c=25,{value:new Promise(function(a){JQUERYBK.ajaxAsync("v1/employee/permission","GET",null,function(b){return a(b)})}),done:!1};case 25:if(void 0===d){c=26;break}c=-1;throw d;case 26:r=
F=a;p=r.permission.split(",");p.includes("read_Stu")&&$("#updateBlock").css("display","block");q=studentInfo.code;JQUERYBK.ajaxAsync("public/media/hinh-the-4x6/"+q+"/thumb/v1","GET",null,function(a){$("#imageCard").attr("src",a)},function(a){$("#imageCard").attr("src","/app/images/no_image.png")});k=optionalAccess(studentInfo.lastUpdatedAt,"","--");l=optionalAccess(studentInfo.imageLastUpdatedAt,"","--");m=optionalAccess(studentInfo.studentStatusLastUpdatedAt,"","--");k="--"===k?"--":convertLocalToUTCDateString(k);
l="--"===l?"--":convertLocalToUTCDateString(l);m="--"===m?"--":convertLocalToUTCDateString(m);$("#info_lastUpdatedAt").html(k);$("#imageLastUpdatedAt").html(l);$("#mssv").html(optionalAccess(studentInfo.code,"","--"));$("#lastName").html(optionalAccess(studentInfo.lastName,"","--"));$("#firstName").html(optionalAccess(studentInfo.firstName,"","--"));$("#dateOfBirth").html(optionalAccess(studentInfo.dateOfBirth,"","--"));e=null===studentInfo.isFemale?"--":studentInfo.isFemale?"Nữ":"Nam";$("#gender").html(e);
$("#idCardNumber").html(optionalAccess(studentInfo.idCardNumber,"","--"));$("#idCardDate").html(optionalAccess(studentInfo.idCardDate,"","--"));$("#idCardPlace").html(optionalAccess(studentInfo.idCardPlace,"","--"));$("#teachingDep").html(optionalAccess(studentInfo.teachingDep,"nameVi","--"));$("#trainingManagementDep").html(optionalAccess(studentInfo.trainingManagementDep,"nameVi","--"));$("#classCode").html(optionalAccess(studentInfo.classCode,"","--"));$("#info_address").html(optionalAccess(studentProfile.contactAddress,
"","--"));$("#info_phoneNumber").html(optionalAccess(studentInfo.phoneNumber,"","--"));$("#orgEmail").html(optionalAccess(studentInfo.orgEmail,"","--"));$("#personalEmail").html(optionalAccess(studentInfo.personalEmail,"","--"));$("#secondEmail").html(optionalAccess(studentInfo.secondEmail,"","--"));$("#startTime").html(optionalAccess(studentInfo.startMonth,"","--")+"/"+optionalAccess(studentInfo.startYear,"","--"));$("#totalSemester").html(optionalAccess(studentInfo.totalSemester,"","--"));$("#totalSemesterMax").html(optionalAccess(studentInfo.totalSemesterMax,
"","--"));$("#trainingTime").html(optionalAccess(studentInfo.trainingTime,"","--"));$("#trainingTimeMax").html(optionalAccess(studentInfo.trainingTimeMax,"","--"));$("#semesterTrainingTime").html(optionalAccess(studentInfo.semesterTrainingTime,"","--"));$("#semesterTrainingTimeMax").html(optionalAccess(studentInfo.semesterTrainingTime,"","--"));$("#applyForYear").html(optionalAccess(studentInfo.applyForYear,"","--"));$("#trainingLevel").html(optionalAccess(studentInfo.trainingLevel,"nameVi","--"));
$("#trainingType").html(optionalAccess(studentInfo.trainingType,"nameVi","--"));f=optionalAccess(studentInfo.major,"type","");switch(f){case "KN":$("#major").html("Khối ngành: "+optionalAccess(studentInfo.major,"code","--")+" - "+optionalAccess(studentInfo.major,"nameVi","--"));break;case "NG":$("#major").html("Ngành: "+optionalAccess(studentInfo.major,"code","--")+" - "+optionalAccess(studentInfo.major,"nameVi","--"));break;case "CN":case "HN":$("#major").html("Chuyên ngành: "+optionalAccess(studentInfo.major,
"code","--")+" - "+optionalAccess(studentInfo.major,"nameVi","--"));break;default:$("#major").html("Chưa được phân ngành")}$("#trainingForms").html(optionalAccess(studentInfo.trainingForms,"nameVi","--"));$("#program").html(optionalAccess(studentInfo.program,"nameVi","--"));$("#extendedSemester").html(optionalAccess(studentInfo.extendedSemester,"","--"));$("#status").html(optionalAccess(studentInfo.status,"name","--"));$("#majorGraduated").html(optionalAccess(studentInfo.majorGraduated,"code","--")+
" - "+optionalAccess(studentInfo.majorGraduated,"nameVi","--"));$("#semesterYearGraduated").html(optionalAccess(studentInfo.semesterYearGraduated,"","--"));$("#graduationDecisionNumber").html(optionalAccess(studentInfo.graduationDecisionNumber,"","--"));$("#graduationDecisionDate").html(optionalAccess(studentInfo.graduationDecisionDate,"","--"));$("#bknet").html(optionalAccess(studentInfo.bknet,"name","--"));$("#bankAccountNumber").html(optionalAccess(studentInfo.bankAccountNumber,"","--"));$("#bank").html(optionalAccess(studentInfo.bank,
"name","--"));$("#ocbCif").html(optionalAccess(studentInfo.ocbCif,"","--"));$("#note").html(optionalAccess(studentInfo.note,"","--"));h=optionalAccess(studentProfile.lastUpdatedAt,"","--");h="--"===h?"--":convertLocalToUTCDateString(h);$("#profile_lastUpdatedAt").html(h);$("#nationality").html(optionalAccess(studentProfile.nationality,"name","--"));$("#placeOfBirth").html(optionalAccess(studentProfile.placeOfBirth,"nameVi","--"));$("#anotherPlaceOfBirth").html(optionalAccess(studentProfile.anotherPlaceOfBirth,
"nameVi","--"));$("#religion").html(optionalAccess(studentProfile.religion,"name","--"));$("#ethnicity").html(optionalAccess(studentProfile.ethnicity,"name","--"));$("#priorityArea").html(optionalAccess(studentProfile.priorityArea,"name","--"));$("#priorityObject").html(optionalAccess(studentProfile.priorityObject,"name","--"));$("#youthUnionJoinDate").html(optionalAccess(studentProfile.youthUnionJoinDate,"","--"));$("#communistPartyJoinDate").html(optionalAccess(studentProfile.communistPartyJoinDate,
"","--"));$("#youthAssociationJoinDate").html(optionalAccess(studentProfile.youthAssociationJoinDate,"","--"));$("#householdNation").html(optionalAccess(studentProfile.householdNation,"","--"));$("#householdProvinceCity").html(optionalAccess(studentProfile.householdProvinceCity,"nameVi","--"));$("#householdDistrict").html(optionalAccess(studentProfile.householdDistrict,"name","--"));$("#householdWard").html(optionalAccess(studentProfile.householdWard,"name","--"));$("#householdNumber").html(optionalAccess(studentProfile.householdNumber,
"","--"));$("#householdAddress").html(optionalAccess(studentProfile.householdAddress,"","--"));$("#provinceCityContact").html(optionalAccess(studentProfile.provinceCityContact,"nameVi","--"));$("#districtContact").html(optionalAccess(studentProfile.districtContact,"name","--"));$("#wardContact").html(optionalAccess(studentProfile.wardContact,"name","--"));$("#houseNumber").html(optionalAccess(studentProfile.houseNumber,"","--"));$("#personalPhoneNumber").html(optionalAccess(studentProfile.personalPhoneNumber,
"","--"));$("#familyPhoneNumber").html(optionalAccess(studentProfile.familyPhoneNumber,"","--"));$("#dormitoryRoom").html(optionalAccess(studentProfile.dormitoryRoom,"","--"));$("#contactAddress").html(optionalAccess(studentProfile.contactAddress,"","--"));$("#fatherName").html(optionalAccess(studentProfile.fatherName,"","--"));$("#fatherYearOfBirth").html(optionalAccess(studentProfile.fatherYearOfBirth,"","--"));$("#fatherJob").html(optionalAccess(studentProfile.fatherJob,"","--"));$("#fatherWorkPlace").html(optionalAccess(studentProfile.fatherWorkPlace,
"","--"));$("#fatherPhoneNumber").html(optionalAccess(studentProfile.fatherPhoneNumber,"","--"));$("#motherName").html(optionalAccess(studentProfile.motherName,"","--"));$("#motherYearOfBirth").html(optionalAccess(studentProfile.motherYearOfBirth,"","--"));$("#motherJob").html(optionalAccess(studentProfile.motherJob,"","--"));$("#motherWorkPlace").html(optionalAccess(studentProfile.motherWorkPlace,"","--"));$("#motherPhoneNumber").html(optionalAccess(studentProfile.motherPhoneNumber,"","--"));$("#guardianName").html(optionalAccess(studentProfile.guardianName,
"","--"));$("#guardianProvinceCity").html(optionalAccess(studentProfile.guardianProvinceCity,"nameVi","--"));$("#guardianDistrict").html(optionalAccess(studentProfile.guardianDistrict,"name","--"));$("#guardianWard").html(optionalAccess(studentProfile.guardianWard,"name","--"));$("#guardianHouseNumber").html(optionalAccess(studentProfile.guardianHouseNumber,"","--"));$("#guardianPhoneNumber").html(optionalAccess(studentProfile.guardianPhoneNumber,"","--"));$("#guardianEmail").html(optionalAccess(studentProfile.guardianEmail,
"","--"));$("#guardianRelationship").html(optionalAccess(studentProfile.guardianRelationship,"","--"));$("#socialNetworkAccount").html(optionalAccess(studentProfile.socialNetworkAccount,"","--"));setStudentHealthInsurance(studentHealthInsurance,studentInfo);$("#updateHealthInsurance").on("click",function(a){a.preventDefault();updateHealthInsurance(g,studentInfo)});modalHealthInsurance.on("show.bs.modal",function(a){getFormDataFn(formHealthInsurance).id?($("#healthInsuranceTitle").html('\x3ci class\x3d"fa fa-edit" style\x3d"color: green;" aria-hidden\x3d"true"\x3e \x3c/i\x3e Cập nhật thông tin Y tế'),
$("#saveHealthInsurance").html("Cập nhật")):($("#healthInsuranceTitle").html('\x3ci class\x3d"fa fa-plus" style\x3d"color: green;" aria-hidden\x3d"true"\x3e \x3c/i\x3e Thêm thông tin Y tế'),$("#saveHealthInsurance").html("Lưu"))}).on("hide.bs.modal",function(){return clearForm(formHealthInsurance)});formHealthInsurance.validate({submitHandler:function(){var a=getFormDataFn(formHealthInsurance),b=a.id,c=function(a){b?Swal.fire({type:"success",title:"Cập nhật thông tin Y tế cho sinh viên thành công"}):
Swal.fire({type:"success",title:"Thêm thông tin Y tế cho sinh viên thành công"});setStudentHealthInsurance(a,studentInfo);modalHealthInsurance.modal("hide")};a.healthInsuranceNum||a.healthExaminationBookNum||a.accidentInsuranceCardNum?b?JQUERYBK.ajaxAsync("v1/student/health-insurance/update/"+g,"PUT",a,function(a){return c(a)}):JQUERYBK.ajaxAsync("v1/student/health-insurance/create","POST",a,function(a){return c(a)}):Swal.fire({type:"warning",title:"Thêm ít nhất 1 thông tin để cập nhật !"})}});handleShowTab(p);
$("#updateStudentProfile").on("click",function(a){a.preventDefault();window.location.href=n+"/he-thong-quan-ly-hoc-vu/quan-ly-sinh-vien/cap-nhat-ho-so-sinh-vien/"+g});showListStudentClass(q);$("#fullName").html('Họ tên: \x3cspan style\x3d"color: #045584"\x3e'+studentInfo.lastName+" "+studentInfo.firstName+" ("+studentInfo.code+") \x3cspan\x3e");b=optionalAccess(studentInfo.status,"","");3===b.id?$("#studentStatus").html(b.name).css({color:"red","font-style":"italic"}):$("#studentStatus").html(b.name).css({color:"#045584",
"font-style":"italic"});courseRegResultRender();tuitionFeesHistoryRender();qnaHistoryRender();activitiesRender();statusDecisionRender();c=-1;default:return{value:void 0,done:!0}}}var c=0,b,h,f,e,m,l,k,q,p,r,F,E,D,C,B,A,z,y,x,w,v,u,n,g,t={next:function(b){return a(b,void 0)},throw:function(b){return a(void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();t[Symbol.iterator]=function(){return this};return t}())});
function setStudentHealthInsurance(a,c){a?($("#studentName").html("Họ và tên: "+optionalAccess(a.student.lastName,"","")+" "+optionalAccess(a.student.firstName,"","")),c=a.lastUpdatedAt?convertLocalToUTCDateString(a.lastUpdatedAt):"",$("#healthInsurance_lastUpdatedAt").html(c),$("#healthExaminationBookNum").html("Số sổ: "+optionalAccess(a.healthExaminationBookNum,"","")),$("#healthExaminationBookContent").html(optionalAccess(a.healthExaminationBookContent,"","")),$("#healthInsuranceNum").html("Số thẻ: "+
optionalAccess(a.healthInsuranceNum,"","")),$("#healthInsuranceContent").html(optionalAccess(a.healthInsuranceContent,"","")),$("#accidentInsuranceCardNum").html("Số thẻ: "+optionalAccess(a.accidentInsuranceCardNum,"","")),$("#accidentInsuranceContent").html(optionalAccess(a.accidentInsuranceContent,"",""))):$("#studentName").html("Họ và tên: "+optionalAccess(c.lastName,"","")+" "+optionalAccess(c.firstName,"",""))}
function updateHealthInsurance(a,c){JQUERYBK.ajaxAsync("v1/student/health-insurance/detail/"+a,"GET",null,function(a){a?($("#id").val(a.id),$("#studentId").val(a.student.id),$("#studentCode").val(a.student.code),$("#form_healthExaminationBookNum").val(a.healthExaminationBookNum),$("#form_healthExaminationBookContent").val(a.healthExaminationBookContent),$("#form_healthInsuranceNum").val(a.healthInsuranceNum),$("#form_healthInsuranceContent").val(a.healthInsuranceContent),$("#form_accidentInsuranceCardNum").val(a.accidentInsuranceCardNum),
$("#form_accidentInsuranceContent").val(a.accidentInsuranceContent)):($("#studentId").val(c.id),$("#studentCode").val(c.code));modalHealthInsurance.modal("show")})}
function handleShowTab(a){a.includes("write_Yte")||a.includes("write_All")?a.includes("read_Yte")&&!a.includes("read_All")&&($("#studentInfo").css("display","none"),$("#tab_StudentInfo").css("display","none"),$("#studentProfile").css("display","none"),$("#tab_StudentProfile").css("display","none"),$("#healthInsurance").addClass("active"),$("#tab_HealthInsurance").addClass("active")):($("#updateHealthInsurance").css("display","none"),$("#modalHealthInsurance").empty())}
function getFormDataFn(a){return a.serializeArray().reduce(function(a,b){a[b.name]=b.value;return a},{})}function clearForm(a){a.find("input,select").val(null).trigger("change").validate().resetForm()}
function showListStudentClass(a){JQUERYBK.ajaxAsync("v1/student-class/list-by-code?mssv\x3d"+a,"get",null,function(a){tblStudentClass.DataTable({destroy:!0,autoWidth:!0,pagingType:"full_numbers",paging:!0,language:{emptyTable:"vi"===language?"\x3cspan style\x3d'color: #cc3c1f'\x3eThông tin Lớp và GVCN chưa được cập nhật! \x3c/span\x3e":"\x3cspan style\x3d'color: #cc3c1f'\x3eClass and Homeroom Teacher information has not been updated! \x3c/span\x3e"},data:a,rowId:"id",columns:[{data:"semesterYear",
defaultContent:"--"},{data:"classMajorBlock",defaultContent:"--"},{data:"classMajorBlock",defaultContent:"--"},{data:"classMajorBlock",defaultContent:"--"},{data:"classMajorBlock",defaultContent:"--"},{data:"employee",defaultContent:"--"},{data:"employee",defaultContent:"--"}],order:[0,"desc"],columnDefs:[{targets:[1,2,3,4,5,6],orderable:!1},{targets:[1,2,3,4],render:function(a,c,f,e){if(a)switch(e.col){case 1:return a.code;case 2:return a.majorBlock?a.majorBlock.code:"--";case 3:return a.majorBlock?
a.majorBlock.applyForYear:"--";case 4:return a.majorBlock?a.majorBlock.teachingDep?a.majorBlock.teachingDep.nameVi:"--":"--"}}},{targets:[5,6],render:function(a,c,f,e){if(a)switch(e.col){case 5:return a.code+" - "+a.lastName+" "+a.firstName;case 6:return a.email}}}]})})}
function courseRegResultRender(){$("#tab_CourseRegResult .student-name").html(studentInfo.code+" - "+studentInfo.lastName+" "+studentInfo.firstName);jTblCourseRegResult.DataTable({destroy:!0,autoWidth:!1,paging:!0,searching:!0,info:!1,data:courseRegResults,columns:[{data:"year",defaultContent:"--",width:"50px"},{data:"semesterCode",defaultContent:"--",width:"100px"},{data:"subjClassGrpCode",defaultContent:"--",width:"100px"},{data:"subjectCode",defaultContent:"--"},{data:"theoryGrpCode",defaultContent:"--",
width:"50px"},{data:"exerciseGrpCode",defaultContent:"--",width:"50px"},{data:"theoryCapacity",defaultContent:"--",width:"50px"},{data:"exerciseCapacity",defaultContent:"--",width:"50px"},{data:"status",defaultContent:"--",width:"50px"},{data:"isConfirmed",defaultContent:"--",width:"50px"},{data:"blockFlagYN",defaultContent:"--",width:"50px"},{data:"result",defaultContent:"--",width:"120px"},{data:"lastUpdatedAt",defaultContent:"--",width:"110px"}],order:[[0,"desc"],[1,"desc"]],columnDefs:[{targets:3,
render:function(a,c,b){return b.subjectCode+" - "+b.subjectName}},{targets:[5,6],className:"text-right",render:function(a){return a?a.toLocaleString():"--"}},{targets:9,render:function(a){return!0===a?"Yes":"No"}},{targets:10,render:function(a){return"1"===a||"Y"===a?"Yes":"No"}},{targets:12,render:function(a){return a?moment(a).format("YYYY-MM-DD HH:mm:ss"):"--"}}]})}
function tuitionFeesHistoryRender(){$("#tab_TuitionFeesHistory .student-name").html(studentInfo.code+" - "+studentInfo.lastName+" "+studentInfo.firstName);jTblTuitionFeeHistory.DataTable({destroy:!0,autoWidth:!1,paging:!0,searching:!0,info:!1,data:tuitionFeesHistory,columns:[{data:"paymentCode",defaultContent:"--",width:"200px"},{data:"shortContent",defaultContent:"--"},{data:"amtToBePaid",defaultContent:"--",width:"60px"},{data:"amtTempPaid",defaultContent:"--",width:"60px"},{data:"amtActualPaid",
defaultContent:"--",width:"60px"},{data:"amtToBeDeducted",defaultContent:"--",width:"60px"},{data:"amtRemaining",defaultContent:"--",width:"60px"},{data:"expectedExpirationDate",defaultContent:"--",width:"120px"},{data:"actualPaidDate",defaultContent:"--",width:"120px"},{data:"isCancelled",defaultContent:"--",width:"60px"}],order:[[7,"desc"]],columnDefs:[{targets:[2,3,4,5,6],className:"text-right",render:function(a){return a?a.toLocaleString():"--"}},{targets:[7,8],render:function(a){return a?moment(a).format("YYYY-MM-DD HH:mm:ss"):
"--"}},{targets:9,render:function(a){return!0===a?"Yes":"No"}}]})}
function qnaHistoryRender(){$("#tab_QnAHistory .student-name").html(studentInfo.code+" - "+studentInfo.lastName+" "+studentInfo.firstName);var a={};qnaHistory.sort(function(a,c){return new Date(a.createdAt)-new Date(c.createdAt)}).forEach(function(b){a[b.ticketId]?a[b.ticketId].msgs.push({hcmutPersonCode:b.msgCreatedByHcmutPersonCode,hcmutPersonFullName:b.msgCreatedByHcmutPersonFullName,message:b.message,createdAt:b.createdAt}):a[b.ticketId]={ticketId:b.ticketId,ticketType:b.ticketType,ticketTitle:b.ticketTitle,
createdAt:b.createdAt,msgs:[{hcmutPersonCode:b.msgCreatedByHcmutPersonCode,hcmutPersonFullName:b.msgCreatedByHcmutPersonFullName,message:b.message,createdAt:b.createdAt}]}});var c=Object.values(a);jTtblQnAThread.DataTable({destroy:!0,autoWidth:!1,paging:!0,searching:!0,info:!1,data:c,columns:[{data:"ticketId",defaultContent:"--",width:"170px"},{data:"ticketId",defaultContent:"--",width:"60px"},{data:"ticketType",defaultContent:"--"},{data:"ticketTitle",defaultContent:"--"},{data:"createdAt",defaultContent:"--",
width:"120px"}],order:[[4,"desc"]],columnDefs:[{targets:0,sortable:!1,render:function(a){return'\x3ca href\x3d"#" class\x3d"btn-show-qna-content" data-ticket-id\x3d"'+a+'"\x3eXem chi tiết nội dung hỏi/đáp\x3c/a\x3e'}},{targets:4,render:function(a){return a?moment(a).format("YYYY-MM-DD HH:mm:ss"):"--"}}],initComplete:function(){jTtblQnAThread.find("a.btn-show-qna-content").on("click",function(b){b.preventDefault();b=$(this).data("ticketId");var c=a[b],f=c.msgs,e=$("#modalQnAContent .modal-body .direct-chat-messages"),
f=f.map(function(a){var b=6!==a.hcmutPersonCode.length,c=$("\x3cdiv/\x3e").html(a.message).text().replace(/\r\n|\n|\r/g,"\x3cbr /\x3e");return'\x3cdiv class\x3d"direct-chat-msg '+(b?"pull-left":"right pull-right")+'" style\x3d"width: 60%"\x3e\n                                \x3cdiv class\x3d"direct-chat-info clearfix"\x3e\n                                    \x3cspan class\x3d"direct-chat-name '+(b?"pull-left":"pull-right")+'"\x3e'+a.hcmutPersonCode+" - "+a.hcmutPersonFullName+'\x3c/span\x3e\n                                    \x3cspan class\x3d"direct-chat-timestamp '+
(b?"pull-right":"pull-left")+'"\x3e'+moment(a.createdAt).format("YYYY-MM-DD HH:mm:ss")+'\x3c/span\x3e\n                                \x3c/div\x3e\n                                \x3cimg class\x3d"direct-chat-img" src\x3d"/app/asset/img/bk_logo.png" alt\x3d"message user"\x3e\n                                \x3cdiv class\x3d"direct-chat-text"\x3e'+c+"\x3c/div\x3e\n                            \x3c/div\x3e"});jModalQnAContent.find(".modal-title").html("\x3cstrong\x3e[#"+b+"] "+c.ticketType+" - "+
c.ticketTitle+"\x3c/strong\x3e");e.html(f);jModalQnAContent.modal("show")})}})}
function activitiesRender(){$("#tab_Activities .student-name").html(studentInfo.code+" - "+studentInfo.lastName+" "+studentInfo.firstName);$("#tab_Activities .num-of-social-work-day").html(activities.numOfSocialWorkDays);jTblActivities.DataTable({destroy:!0,autoWidth:!1,paging:!0,searching:!0,info:!1,data:activities.participationActivities,columns:[{data:"activityId",defaultContent:"--",width:"60px"},{data:"activityName",defaultContent:"--",width:"300px"},{data:"activityLocation",defaultContent:"--",
width:"300px"},{data:"activityStartDate",defaultContent:"--",width:"60px"},{data:"numberOfDays",defaultContent:"--",width:"60px"},{data:"numberOfConversionDays",defaultContent:"--",width:"60px"},{data:"hasProof",defaultContent:"--",width:"60px"},{data:"isConfirmed",defaultContent:"--",width:"60px"},{data:"status",defaultContent:"--",width:"60px"}],order:[[3,"desc"]],columnDefs:[{targets:[0,5,6,7,8],orderable:!1},{targets:[6,7],render:function(a){return a?"Yes":"No"}},{targets:8,render:function(a){return"AF"===
a?"Kết thúc":"--"}}]})}
function statusDecisionRender(){var a=_.orderBy(statusDecisions,["yearSemesterCode",function(a){return moment(a.decisionDate,"DD/MM/YYYY").toDate()}],["desc","desc"]);tblStatusDecision.DataTable({destroy:!0,autoWidth:!0,paging:!1,searching:!1,ordering:!1,info:!1,data:a,language:{emptyTable:"vi"===language?"\x3cspan style\x3d'color:red'\x3e Quyết định sinh viên chưa được cập nhật \x3c/span\x3e":"\x3cspan style\x3d'color:red'\x3e Student decisions have not been updated \x3c/span\x3e"},columns:[{data:"yearSemesterName",
defaultContent:"--"},{data:"decisionReason",defaultContent:"--"},{data:"decisionCode",defaultContent:"--"},{data:"decisionDate",defaultContent:"--"},{data:"lastUpdatedAt",defaultContent:"--"},{data:"type",defaultContent:"--"}]})};